backoffice/urls.py
from backoffice import views
from django.urls import path

app_name = 'backoffice'

urlpatterns = [
    path('search/', views.search, name='search'),
    path('', views.index, name='index'),

    path('contact/<int:contact_id>/', views.contact, name='contact'),
    path('contact/create/', views.create, name='create'),
    path('contact/<int:contact_id>/update/', views.update, name='update'),
    path('contact/<int:contact_id>/delete/', views.delete, name='delete'),

    path('user/register/', views.register, name='register'),
    path('user/login/', views.login_view, name='login'),
    path('user/update/', views.user_update, name='user_update'),
    path('user/logout/', views.logout_view, name='logout'),
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings 


urlpatterns = [
    path('contact-manager/', include('backoffice.urls')),
    path('', include('landingpage.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backoffice/models.py
from django.db import models

class Category(models.Model):
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    name = models.CharField ('Category', max_length=50)

    def __str__(self) -> str:
        return self.name


class Contact(models.Model):
    first_name = models.CharField('First Name', max_length=50)
    last_name = models.CharField('Last Name', max_length=50)
    phone = models.CharField('Mobile', max_length=50, blank=True)
    email = models.EmailField('Email', max_length=50)
    city = models.CharField('City', max_length=50, blank=True)
    country = models.CharField('Country', max_length=50, blank=True)
    created_at = models.DateField('Created at', auto_now_add=True)
    updated_at = models.DateField('Updated at', auto_now=True)
    status = models.BooleanField('Ative', default=True)
    category = models.ForeignKey(
        Category, 
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'

backoffice/forms.py
from django import forms
from django.contrib.auth import password_validation
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from . import models

class ContactForm(forms.ModelForm):
    
    class Meta:
        model = models.Contact
        fields = ('first_name', 'last_name', 'phone', 'email', 'category', 'city', 'country',)

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if models.Contact.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise ValidationError('Email already exists.')
        return email
    
    def clean_phone(self):
        phone = self.cleaned_data.get('phone')

        for char in phone:
            if not char.isdigit() and char != '+':
                raise ValidationError('Phone number should contain only digits or "+" symbol.')
        return phone
    

class RegisterForm(UserCreationForm):
    first_name = forms.CharField(
        required=True,
        min_length=3,
    )
    last_name = forms.CharField(
        required=True,
        min_length=3,
    )
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username', 'password1', 'password2',
        )

    def clean_email(self):
        email = self.cleaned_data.get('email')

        if User.objects.filter(email=email).exists():
            self.add_error(
                'email',
                ValidationError('Email already exists.', code='invalid')
            )

        return email
    

class RegisterUpdateForm(forms.ModelForm):
    first_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.',
        error_messages={
            'min_length': 'Please, add more than 2 letters.'
        }
    )
    last_name = forms.CharField(
        min_length=2,
        max_length=30,
        required=True,
        help_text='Required.'
    )

    password1 = forms.CharField(
        label="Password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text=password_validation.password_validators_help_text_html(),
        required=False,
    )

    password2 = forms.CharField(
        label="Password 2",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        help_text='Use the same password as before.',
        required=False,
    )

    class Meta:
        model = User
        fields = (
            'first_name', 'last_name', 'email',
            'username',
        )

    def save(self, commit=True):
        cleaned_data = self.cleaned_data
        user = super().save(commit=False)
        password = cleaned_data.get('password1')

        if password:
            user.set_password(password)

        if commit:
            user.save()

        return user

    def clean(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 or password2:
            if password1 != password2:
                self.add_error(
                    'password2',
                    ValidationError('Passwords do not match.')
                )

        return super().clean()

    def clean_email(self):
        email = self.cleaned_data.get('email')
        current_email = self.instance.email

        if current_email != email:
            if User.objects.filter(email=email).exists():
                self.add_error(
                    'email',
                    ValidationError('Email already exists.', code='invalid')
                )

        return email

    def clean_password1(self):
        password1 = self.cleaned_data.get('password1')

        if password1:
            try:
                password_validation.validate_password(password1)
            except ValidationError as errors:
                self.add_error(
                    'password1',
                    ValidationError(errors)
                )

        return password1

backoffice/views/contact_forms.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from backoffice.forms import ContactForm
from backoffice.models import Contact


@login_required(login_url=('backoffice:login'))
def create(request):
    form_action = reverse('backoffice:create')
    if request.method == 'POST':
        form = ContactForm(request.POST)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            form.save()
            return redirect('backoffice:index')

        return render(
            request,
            'backoffice/create.html',
            context
        )
    
    context = {
            'form': ContactForm(),
            'form_action': form_action,
        }
    
    return render(
            request,
            'backoffice/create.html',
            context
        )


@login_required(login_url=('backoffice:login'))
def update(request, contact_id):
    contact = get_object_or_404(Contact, pk=contact_id, status=True)
    form_action = reverse('backoffice:update', args=(contact_id,))
    
    if request.method == 'POST':
        form = ContactForm(request.POST, instance=contact)

        context = {
            'form': form,
            'form_action': form_action,
        }

        if form.is_valid():
            form.save()
            return redirect('backoffice:index')

        return render(
            request,
            'backoffice/update.html',
            context
        )
    
    context = {
            'form': ContactForm(instance=contact),
            'form_action': form_action,
        }
    
    return render(
            request,
            'backoffice/update.html',
            context
        )


@login_required(login_url=('backoffice:login'))
def delete(request, contact_id):
    contact = get_object_or_404(
        Contact, pk=contact_id, status=True
    )
    confirmation = request.POST.get('confirmation', 'no')

    if confirmation == 'yes':
        contact.delete()
        return redirect('backoffice:index')

    return render(
        request,
        'backoffice/contact.html',
        {
            'contact': contact,
            'confirmation': confirmation,
        }
    )

backoffice/views/contact_views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.core.paginator import Paginator
from django.db.models import Q
from backoffice.models import Contact


@login_required(login_url=('backoffice:login'))
def index(request):
    contacts = Contact.objects.filter(status=True).order_by('first_name')

    paginator = Paginator(contacts, 15)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Contact Board'
    }

    return render(
        request,
        'backoffice/index.html',
        context
    )


@login_required(login_url=('backoffice:login'))
def search(request):
    search_value = request.GET.get('q', '').strip()

    if search_value == '':
        return redirect('backoffice:index')

    contacts = Contact.objects \
        .filter(status=True)\
        .filter(
            Q(first_name__icontains=search_value) |
            Q(last_name__icontains=search_value) |
            Q(phone__icontains=search_value) |
            Q(email__icontains=search_value)
        )\
        .order_by('first_name')
    
    paginator = Paginator(contacts, 15)  # Show 25 contacts per page.
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'site_title': 'Search - '
    }

    return render(
        request,
        'backoffice/index.html',
        context
    )


@login_required(login_url=('backoffice:login'))
def contact(request, contact_id):
    single_contact = get_object_or_404(Contact, pk=contact_id, status=True)

    context = {
        'contact': single_contact,
    }

    return render(
        request,
        'backoffice/contact.html',
        context
    )

backoffice/views/user_forms.py
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import redirect, render

from backoffice.forms import RegisterForm, RegisterUpdateForm

@login_required(login_url=('backoffice:login'))
def register(request):
    form = RegisterForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('backoffice:login')


    return render(
        request,
        'backoffice/register.html',
        {
            'form': form
        }
    )

@login_required(login_url=('backoffice:login'))
def user_update(request):
    form = RegisterUpdateForm(instance=request.user)

    if request.method != 'POST':
        return render(
            request,
            'backoffice/user_update.html',
            {
                'form': form
            }
        )

    form = RegisterUpdateForm(data=request.POST, instance=request.user)

    if not form.is_valid():
        return render(
            request,
            'backoffice/user_update.html',
            {
                'form': form
            }
        )

    form.save()
    return redirect('backoffice:index')


def login_view(request):
    form = AuthenticationForm(request)

    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)

        if form.is_valid():
            user = form.get_user()
            auth.login(request, user)
            return redirect('backoffice:index')

    return render(
        request,
        'backoffice/login.html',
        {
            'form': form
        }
    )


@login_required(login_url=('backoffice:login'))
def logout_view(request):
    auth.logout(request)
    return redirect('backoffice:login')

backoffice/templates/backoffice/contact.html
{% extends "backoffice/main_layout.html" %}

{% block content %}
    <div class="single-contact">
        <h1 class="single-contact-name">
           {{ contact.first_name }} {{ contact.last_name }}
        </h1>

        <p><b>E-mail:</b> {{ contact.email }}</p>
        <p><b>Mobile:</b> {{ contact.phone }}</p>
        <p><b>City:</b> {{ contact.city }}</p>
        <p><b>Country:</b> {{ contact.country }}</p>
        <p><b>Category:</b> {{ contact.category.name }}</p>
        <p><b>Created Date:</b> {{ contact.created_at }}</p>
    </div>
    
    <div class="contact-links">
      <a class="btn btn-link" href="{% url 'backoffice:update' contact.id %}">Update</a>

      <form action="{% url 'backoffice:delete' contact.id %} " method="POST">
          {% csrf_token %}

          {% if confirmation == 'no' %}
              <input type="hidden" name="confirmation" value="yes">
              <button class="btn btn-link btn-delete" type="submit">Confirm</button>
          {% else %}
          <button class="btn btn-link btn-delete" type="submit">Delete</button>
          {% endif %}
      </form>
    </div>
{% endblock content %}

backoffice/templates/backoffice/create.html
{% extends "backoffice/main_layout.html" %}

{% block content %}

<div class="form-wrapper">

  <h2>New Contact</h2>

  <form 
    action="{{ form_action }}"
    method="POST"
  >
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
    </div>


    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

backoffice/templates/backoffice/index.html
{% extends "backoffice/main_layout.html" %}

{% block content %}
    {% if page_obj %}
        <div class="responsive-table">
            <table class="contacts-table">
                <caption class="table-caption">
                    Contacts
                </caption>

                <thead>
                    <tr class="table-row table-row-header">
                        <th class="table-header">First Name</th>
                        <th class="table-header">Last Name</th>
                        <th class="table-header">Mobile</th>
                        <th class="table-header">Email</th>
                        <th class="table-header">City</th>
                        <th class="table-header">Country</th>
                    </tr>
                </thead>

                <tbody>
                    {% for contact in page_obj %}
                        <tr class="table-row">
                            <td class="table-cel">
                                <a class="table-link" href="{% url 'backoffice:contact' contact.id %}">
                                    {{ contact.first_name }}
                                </a>
                            </td>
                            <td class="tablecel">
                                {{ contact.last_name }}
                            </td>
                            <td class="tablecel">
                                {{ contact.phone }}
                            </td>
                            <td class="tablecel">
                                {{ contact.email }}
                            </td>
                            <td class="tablecel">
                                {{ contact.city }}
                            </td>
                            <td class="tablecel">
                                {{ contact.country }}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="single-contact">
            <h1 class="single-contact-name">
            Contact not found.
            </h1>
      </div>
    {% endif %}

{% endblock content %}

backoffice/templates/backoffice/login.html
{% extends "backoffice/main_layout.html" %}

{% block content %}

<div class="form-wrapper">

  <h2>Login</h2>

  <form 
    action="{{ form_action }}"
    method="POST"
  >
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
    </div>


    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

backoffice/templates/backoffice/main_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'backoffice/css/style.css' %}">
    <title>{{ site_title }}</title>
</head>
<body>

    <header class="header">
        <h1 class="header-heading">
          <a href="{% url 'backoffice:index' %}" class="header-link">
            Contact Manager
          </a>
        </h1>
      
        {% if user.is_authenticated %} 
          <nav class="menu-container">
            <ul class="menu-list">
              <li class="menu-item">
                <a href="{% url 'backoffice:create' %}" class="menu-link">New Contact</a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backoffice:register' %}" class="menu-link">Add User</a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backoffice:user_update' %}" class="menu-link">Account Settings</a>
              </li>
              <li class="menu-item">
                <a href="{% url 'backoffice:logout' %}" class="menu-link">Logout</a>
              </li>
            </ul>
          </nav>
        
          <div class="search">
            <form 
              action="{% url 'backoffice:search' %}" 
              method="GET"
            >
            <input 
              type="search" 
              class="search-input"
              placeholder="Search"
              id="search"
              name="q"
              value="{{ request.GET.q.strip }}"
            >
            </form>
          </div>
        {% endif %}
    </header>

    <main class="content">
        {% block content %}
        {% endblock content %}

        {% if page_obj %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1&q={{ request.GET.q.strip }}">&laquo; first</a>
                        <a href="?page={{ page_obj.previous_page_number }}&q={{ request.GET.q.strip }}">previous</a>
                    {% endif %}
            
                    <span class="current">
                        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                    </span>
            
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}&q={{ request.GET.q.strip }}">next</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}&q={{ request.GET.q.strip }}">last &raquo;</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
    </main>

</body>
</html>

backoffice/templates/backoffice/register.html
{% extends "backoffice/main_layout.html" %}

{% block content %}

<div class="form-wrapper">

  <h2>Register</h2>

  <form 
    action="{{ form_action }}"
    method="POST"
  >
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
    </div>


    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

backoffice/templates/backoffice/update.html
{% extends "backoffice/main_layout.html" %}

{% block content %}

<div class="form-wrapper">

  <h2>Update Contact</h2>

  <form 
    action="{{ form_action }}"
    method="POST"
  >
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
    </div>


    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}

backoffice/templates/backoffice/user_update.html
{% extends "backoffice/main_layout.html" %}

{% block content %}

<div class="form-wrapper">

  <h2>Account Settings</h2>

  <form 
    action="{{ form_action }}"
    method="POST"
  >
    {% csrf_token %}

    <div class="form-content">
      {% for field in form %}
        <div class="form-group">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {{ field.errors }}
        </div>
      {% endfor %}
    </div>


    <div class="form-content">
      <div class="form-group">
        <button class="btn" type="submit">Send</button>
      </div>
    </div>

  </form>
</div>
{% endblock content %}